---
- hosts: "{{ hosts }}"
  tasks:
  - name: Creamos un directorio temporal para descargar el apache
    win_file:
      path: C:\Temp
      state: directory
    tags: install
  - name: Download apache 
    win_get_url:
      url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
      dest: C:\Temp
    tags: [ never, install ]
  - name: Install package
    win_package: 
      path: 'C:\Temp\httpd-2.2.25-win32-x86-no_ssl.msi'
      state: present
    tags: [ never, install ]
  - name: uninstall package
    win_package: 
      path: 'C:\Temp\httpd-2.2.25-win32-x86-no_ssl.msi'
      state: absent
    tags: [ never, uninstall ]